### ISSUE TITLE
Task: Add versioning to the DockerHub images

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/app-actigraphy#38]
### Description

It'll be important to keep an accurate version record for user reports of bugs. To that end, Docker images should have a version tag.

### Tasks

- [ ] Add a create image action upon release.
- [ ] The new image should be added as a new version, as well as overwrite latest. 
- [ ] A 'main' version will be retained that remains up-to-date with the main branch.
